Fix load issues management command
mozilla/code-review pull request #1476
Opened 2022-12-13 10:58 UTC by vrigal

2022-12-13 13:29 UTC, La0 requested changes

2022-12-13 13:29 UTC, La0 commented on backend/code_review_backend/issues/management/commands/load_issues.py
> +                "No repository found with URL {data['repository']}, skipping."
This lacks the `f-string` prefix

2022-12-13 13:51 UTC, La0 reviewed
I ran the script against the prod dump, and I'm getting conflicts issues on Diff (already present issue in DB with the same PHID, but not the same ID / revision link ?)

Can you test it against the same DB please ?

2022-12-14 08:32 UTC, vrigal commented
That error happens because a diff was already existing, and has been created from another repository.
From what I understand this is intended behavior at diff's level (https://github.com/mozilla/code-review/pull/273).

I made the change to get_or_create the diff according to its ID only.

2023-03-14 09:33 UTC, marco-c approved these changes

2023-03-14 09:33 UTC, merged