Allow issues bulk creation with existing hashes
mozilla/code-review pull request #2502
Opened 2024-11-04 16:48 UTC by vrigal

Closes #2474

2024-11-04 18:54 UTC, La0 requested changes

2024-11-04 18:54 UTC, La0 commented on backend/code_review_backend/issues/tests/test_api.py
> +        self.assertListEqual([i.id for i in issues], [i.id for i in new_issues[:2]])
It would be cleaner to check the hash value, hardcoding the hashes there: we make 100% sure we only have expected non-duplicated values

2024-11-06 08:04 UTC, La0 approved these changes
Well done, this now works with repeated calls to the bot :+1:

2024-11-06 12:51 UTC, Archaeopteryx approved these changes

2024-11-13 10:13 UTC, merged